GET http://localhost:8000/books/
Accept: application/json;charset=UTF-8

> {%
   client.test("Get books", function() {
    client.assert(response.status === 200, "Response status is not 200")
})
%}

###
